# Generated by Django 5.1.7 on 2025-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_logo_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
