# Generated by Django 5.1.7 on 2025-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_school_last_logo_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='last_logo_update',
        ),
        migrations.AddField(
            model_name='school',
            name='logo_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
