# Generated by Django 5.1.7 on 2025-04-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_school_last_logo_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo_last_updated',
        ),
        migrations.RemoveField(
            model_name='school',
            name='logo_url',
        ),
    ]
