# Generated by Django 5.1.7 on 2025-04-07 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_school_logo_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
