# Generated by Django 5.1.7 on 2025-04-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_school_options_school_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.RemoveField(
            model_name='school',
            name='created_at',
        ),
    ]
