# Generated by Django 5.1.7 on 2025-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_school_options_remove_school_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationyear',
            options={'ordering': ['-year'], 'verbose_name': 'Mezuniyet Yılı', 'verbose_name_plural': 'Mezuniyet Yılları'},
        ),
        migrations.AlterUniqueTogether(
            name='graduationyear',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='graduationyear',
            name='password',
        ),
        migrations.RemoveField(
            model_name='graduationyear',
            name='school',
        ),
    ]
