# Generated by Django 5.1.7 on 2025-04-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_graduationyear_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationyear',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='graduationyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_years', to='users.school'),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='graduationyear',
            unique_together={('school', 'year')},
        ),
    ]
