# Generated by Django 5.1.7 on 2025-04-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_graduationyear_password_graduationyear_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationyear',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_years', to='users.school'),
        ),
    ]
