# Generated by Django 5.1.7 on 2025-04-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_graduationyear_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationyear',
            name='password',
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduation_years', to='users.school'),
        ),
    ]
