# Generated by Django 5.1.7 on 2025-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_graduationyear_password_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduationyear',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='graduationyear',
            name='school',
        ),
    ]
