# Generated by Django 5.1.7 on 2025-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_edited_department',
            field=models.BooleanField(default=False, verbose_name='Bölüm düzenlendi mi'),
        ),
    ]
