# Generated by Django 5.1.7 on 2025-04-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_has_edited_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Motto'),
        ),
    ]
