# Generated by Django 5.1.7 on 2025-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='quote',
        ),
        migrations.AddField(
            model_name='customuser',
            name='motto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motto'),
        ),
    ]
