# Generated by Django 5.1.7 on 2025-04-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_yearbookpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearbookPage',
        ),
    ]
