# Generated by Django 5.1.7 on 2025-05-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cover_photo',
        ),
    ]
