# Generated by Django 5.1.7 on 2025-05-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_customuser_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='graduation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='graduation_photos/', verbose_name='Mezuniyet Fotoğrafı'),
        ),
    ]
