# Generated by Django 5.1.7 on 2025-05-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_graduation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_notes_photo',
            field=models.ImageField(blank=True, null=True, upload_to='my_notes_photos/', verbose_name='Notlarım Fotoğrafı'),
        ),
    ]
