# Generated by Django 5.1.7 on 2025-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customuser_my_notes_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='my_notes_photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes_graduation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='notes_graduation_photos/', verbose_name='Notlar Sayfası Mezuniyet Fotoğrafı'),
        ),
    ]
