# Generated by Django 5.1.7 on 2025-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='E-posta bildirimleri aktif mi?'),
        ),
    ]
