# Generated by Django 5.1.7 on 2025-06-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_customuser_email_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications_enabled',
        ),
    ]
