# Generated by Django 5.1.7 on 2025-06-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_customuser_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Yeni not aldığında e-posta bildirimi almak istiyor musunuz?', verbose_name='E-posta Bildirimleri Aktif'),
        ),
    ]
