# Generated by Django 5.1.7 on 2025-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_customuser_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
