# Generated by Django 5.1.7 on 2025-06-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_note_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='hidden',
        ),
        migrations.AddField(
            model_name='note',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
