# Generated by Django 5.1.7 on 2025-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_note_hidden_note_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='visible',
        ),
        migrations.AddField(
            model_name='message',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
