services:
  - type: web
    name: yillik-site
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn uni_yillik.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yillik-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yillik-site.onrender.com"
      - key: DEFAULT_DOMAIN
        value: "yillik-site.onrender.com"
      - key: RESEND_API_KEY
        sync: false  # Dashboard'dan manuel girilecek
      - key: RESEND_FROM_EMAIL
        value: "onboarding@resend.dev"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: yillik-db
    plan: free

