"""
Django settings for uni_yillik project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
import resend
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = BASE_DIR / '.env'

# .env dosyası varsa yükle (Render'da olmaz, ortam değişkenleri dashboard'dan gelir)
if dotenv_path.exists():
    print(f"[settings.py] Loading .env from: {dotenv_path}")
    load_dotenv(dotenv_path)
else:
    print("[settings.py] .env file not found, using system environment variables")

if not os.getenv("RESEND_API_KEY"):
    print("⚠️ RESEND_API_KEY is NOT set in settings.py")
else:
    print("✅ RESEND_API_KEY loaded in settings.py")

RESEND_API_KEY = os.getenv('RESEND_API_KEY')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', 'noreply@yillik.site')
DEFAULT_FROM_EMAIL = RESEND_FROM_EMAIL

DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1")

if DEBUG:
    print(f"RESEND_API_KEY: {'Set' if RESEND_API_KEY else 'Not set'}")
    print(f"RESEND_FROM_EMAIL: {RESEND_FROM_EMAIL}")
    print(f"DEFAULT_FROM_EMAIL: {DEFAULT_FROM_EMAIL}")

# .env dosyası kontrolü kaldırıldı — Render ortam değişkenlerini dashboard'dan alır



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'yillik.site,www.yillik.site').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uni_yillik.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            BASE_DIR / "users" / "templates",],
        'APP_DIRS': True,  # Uygulama içindeki templates dizinlerini kullan
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'uni_yillik.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic için
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'school_dashboard'
LOGOUT_REDIRECT_URL = 'login_register'

# Mesaj ayarları
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Google API Settings
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
GOOGLE_CSE_ID = os.getenv('GOOGLE_CSE_ID')

# For password reset email construction
DEFAULT_DOMAIN = '127.0.0.1:8000'
GOOGLE_CSE_ID = "64ea4b8fcead34b1a"

# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True

# Email backend - using console in development, no default in production
# Note: We're using direct API calls to Resend, so we don't need Django's email backend
# This is just for any Django auth emails if they're used
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # In production, either don't set this or use a proper email backend
    # since we're using direct Resend API calls for verification emails
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For password reset email construction
DEFAULT_DOMAIN = 'yillik.site'  # Production domain

# Make sure cookies are sent with same-site requests
CSRF_TRUSTED_ORIGINS = [
    'https://yillik.site',
    'https://www.yillik.site',
    'https://209.38.229.98'
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'email_debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'email_debug': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}